/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ListsRouteImport } from './routes/lists'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ListsIndexRouteImport } from './routes/lists.index'
import { Route as ListsListIdRouteImport } from './routes/lists.$listId'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'

const ListsRoute = ListsRouteImport.update({
  id: '/lists',
  path: '/lists',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListsIndexRoute = ListsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ListsRoute,
} as any)
const ListsListIdRoute = ListsListIdRouteImport.update({
  id: '/$listId',
  path: '/$listId',
  getParentRoute: () => ListsRoute,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/lists': typeof ListsRouteWithChildren
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/lists/$listId': typeof ListsListIdRoute
  '/lists/': typeof ListsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/lists/$listId': typeof ListsListIdRoute
  '/lists': typeof ListsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/lists': typeof ListsRouteWithChildren
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/lists/$listId': typeof ListsListIdRoute
  '/lists/': typeof ListsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/lists'
    | '/demo/tanstack-query'
    | '/lists/$listId'
    | '/lists/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/demo/tanstack-query' | '/lists/$listId' | '/lists'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/lists'
    | '/demo/tanstack-query'
    | '/lists/$listId'
    | '/lists/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ListsRoute: typeof ListsRouteWithChildren
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/lists': {
      id: '/lists'
      path: '/lists'
      fullPath: '/lists'
      preLoaderRoute: typeof ListsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lists/': {
      id: '/lists/'
      path: '/'
      fullPath: '/lists/'
      preLoaderRoute: typeof ListsIndexRouteImport
      parentRoute: typeof ListsRoute
    }
    '/lists/$listId': {
      id: '/lists/$listId'
      path: '/$listId'
      fullPath: '/lists/$listId'
      preLoaderRoute: typeof ListsListIdRouteImport
      parentRoute: typeof ListsRoute
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ListsRouteChildren {
  ListsListIdRoute: typeof ListsListIdRoute
  ListsIndexRoute: typeof ListsIndexRoute
}

const ListsRouteChildren: ListsRouteChildren = {
  ListsListIdRoute: ListsListIdRoute,
  ListsIndexRoute: ListsIndexRoute,
}

const ListsRouteWithChildren = ListsRoute._addFileChildren(ListsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ListsRoute: ListsRouteWithChildren,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
